[package]
name = "list-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.30"
crossterm = "0.27"
arboard = "3.6"
tui-textarea = "0.4"
unicode-width = "0.1"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
regex = "1.12.2"

[dev-dependencies]
